context:
  version: "2.4.21"

package:
  name: kotlin
  version: ${{ version }}

source:
  url: https://github.com/JetBrains/kotlin/archive/v${{ version }}.tar.gz
  sha256: 6ee2c2026ab8fdde96e6f14b84262dfa3ac22ea7510e82b42489d846735b9202

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk =17
  run:
    - openjdk

tests:
  - script:
      - kapt -help
      - kotlin -help
      - kotlinc -help

about:
  license: Apache-2.0
  license_file:
    - license/LICENSE.txt
    - license/third_party/
  summary: The Kotlin Programming Language.
  homepage: https://github.com/JetBrains/kotlin
  repository: https://github.com/JetBrains/kotlin

extra:
  recipe-maintainers:
    - danielnachun
