context:
  version: "2.3.10"

package:
  name: kotlin
  version: ${{ version }}

source:
  url: https://github.com/JetBrains/kotlin/archive/v${{ version }}.tar.gz
  sha256: be043d1c0347b00425c542bb4b3aa6396d167b2ff10ecf475ba7b0ef44c7b7f7

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk =21
  run:
    - openjdk

tests:
  - script:
      - kapt -help
      - kotlin -help
      - kotlinc -help

about:
  license: Apache-2.0
  license_file:
    - license/LICENSE.txt
    - license/third_party/
  summary: The Kotlin Programming Language.
  homepage: https://github.com/JetBrains/kotlin
  repository: https://github.com/JetBrains/kotlin

extra:
  recipe-maintainers:
    - danielnachun
